### ISSUE TITLE
login 方法 sql写的有问题

### ISSUE THREAD

**Issue by dianxiaopao** [193Eric/vue-node-demo#5]
password 需要用引号引起来，不然sql报错
app.post('/login', function (req, res) {
  sql.query('select user from person where user="' + req.body.username + '" and password="' + req.body.password+'"', function (err, rows) {
    if (err || rows.length == 0) {
      console.log(err)
      res.send({code: 0})
    }else {
      res.send({code: 1})
    }
  })
})

**Comment by 193Eric** [comment]
嗯嗯，修改了
