### ISSUE TITLE
登陆永远不成功

### ISSUE THREAD

**Issue by mrzhouxu** [193Eric/vue-node-demo#8]
api/index.js   87行
原本是这样：
`sql.query('select user from person where user="' + req.body.username + '" and password="' + req.body.password, function (err, rows) {`
一直登陆失败

但是，改成这样：
`sql.query('select user from person where user="' + req.body.username + '" and password="' + req.body.password+'"', function (err, rows) {`
就可以登陆了

区别是：req.body.password后面少个双引号

**Comment by 193Eric** [comment]
已修复，3Q
